name: zone_trader
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_core: ^2.8.0
  firebase_auth: ^4.2.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  rename: ^3.0.1
  intl: ^0.19.0
  gsheets: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.jpg"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Australia.jpeg
    - images/Arabia.jpeg
    - images/Algeria.jpeg
    - images/India.jpeg
    - images/Antarctica.jpeg
    - images/Romania.jpeg
    - images/Mexico.jpeg
    - images/Argentina.jpeg
    - images/China.jpeg
    - images/Canada.jpeg
    - images/Egypt.jpeg
    - images/Malaysia.jpeg
    - images/Russia.jpeg
    - images/USA.jpeg
    - images/Brazil.jpeg
    - images/Kazakhstan.jpeg
    - images/Philippines.jpeg
    - images/Congo.jpeg
    - images/Greenland.jpeg
    - images/Peru.jpeg
    - images/Indonesia.jpeg
    - images/Sweden.jpeg
    - images/Venezuela.jpeg
    - images/Libya.jpeg
    - images/Iran.jpeg
    - images/Mongolia.jpeg
    - images/Chad.jpeg
    - images/Niger.jpeg
    - images/Mali.jpeg
    - images/Africa.jpeg
    - images/Ethiopia.jpeg
    - images/Pakistan.jpeg
    - images/Turkey.jpeg
    - images/Chile.jpeg
    - images/Myanmar.jpeg
    - images/Afghanistan.jpeg
    - images/Ukraine.jpeg
    - images/Kenya.jpeg
    - images/France.jpeg
    - images/Yemen.jpeg
    - images/Spain.jpeg
    - images/Turkmenistan.jpeg
    - images/Guinea.jpeg
    - images/Morocco.jpeg
    - images/Sweden.jpeg
    - images/Norway.jpeg
    - images/Poland.jpeg
    - images/Italy.jpeg
    - images/Nepal.jpeg
    - images/Sudan.jpeg
    - images/Algiers.png
    - images/Ankara.png
    - images/Beijing.png
    - images/Bucharest.png
    - images/BuenosAires.png
    - images/Canberra.png
    - images/McMurdo.png
    - images/MexicoCity.png
    - images/Moscow.png
    - images/NewDelhi.png
    - images/Ottawa.png
    - images/Putrajaya.png
    - images/Riyadh.png
    - images/AddisAbaba.png
    - images/Ashgabat.png
    - images/Astana.png
    - images/Bamako.png
    - images/Brasilia.png
    - images/Caracas.png
    - images/Cairo.png
    - images/Congo.jpeg
    - images/Conakry.png
    - images/Islamabad.png
    - images/Jakarta.png
    - images/Kabul.png
    - images/Khartoum.png
    - images/Kinshasa.png
    - images/Kyiv.png
    - images/Lima.png
    - images/Madrid.png
    - images/Manila.png
    - images/N'Djamena.png
    - images/Nairobi.png
    - images/Naypyidaw.png
    - images/Niamey.png
    - images/Nuuk.png
    - images/Oslo.png
    - images/Paris.png
    - images/Pretoria.png
    - images/Rabat.png
    - images/Rome.png
    - images/Sana'a.png
    - images/Santiago.png
    - images/Stockholm.png
    - images/Tehran.png
    - images/Tripoli.png
    - images/Ulaanbaatar.png
    - images/Warsaw.png
    - images/Washington.png

    - images/start.jpeg
    - images/intro.jpeg
    - images/up.png
    - images/htp1.png
    - images/htp1signout.png
    - images/htp1tr.png
    - images/htp1trsignout.png
    - images/htp1jp.png
    - images/htp1jpsignout.png
    - images/htp1es.png
    - images/htp1essignout.png
    - images/settings.png
    - images/settingsreload.png
    - images/settingshome.png
    - images/settingstr.png
    - images/settingsreloadtr.png
    - images/settingshometr.png
    - images/settingses.png
    - images/settingsreloades.png
    - images/settingshomees.png
    - images/settingsjp.png
    - images/settingsreloadjp.png
    - images/settingshomejp.png
    - images/game.png
    - images/gameboughtcountries.png
    - images/gamenotboughtcountries.png
    - images/gamecountrylist.png
    - images/gamehome.png
    - images/gamemoney.png
    - images/gamenickname.png
    - images/gamereload.png
    - images/gamepopup.png
    - images/gamepopupinfos.png
    - images/gamepopupbuyorcancel.png
    - images/gamepopuptr.png
    - images/gamepopupinfostr.png
    - images/gamepopupbuyorcanceltr.png
    - images/gamepopupes.png
    - images/gamepopupinfoses.png
    - images/gamepopupbuyorcanceles.png
    - images/gamepopupjp.png
    - images/gamepopupinfosjp.png
    - images/gamepopupbuyorcanceljp.png
    - images/mycountrylistinfos.png
    - images/mycountrylistinfostr.png
    - images/mycountrylistinfoses.png
    - images/mycountrylistinfosjp.png
    - images/mycountrylistnothing.png
    - images/mycountrylistnothingtr.png
    - images/mycountrylistnothinges.png
    - images/mycountrylistnothingjp.png
    - images/mycountrylistpopupinfos.png
    - images/mycountrylistpopupinfostr.png
    - images/mycountrylistpopupinfoses.png
    - images/mycountrylistpopupinfosjp.png
    - images/mycountrylistpopupsellorcancel.png
    - images/mycountrylistpopupsellorcanceltr.png
    - images/mycountrylistpopupsellorcanceles.png
    - images/mycountrylistpopupsellorcanceljp.png
    - images/logo.jpg
    - assets/sounds/bought.mp3
    - assets/sounds/homeinitpopup.mp3
    - assets/sounds/pagechanged.mp3
    - assets/sounds/close.mp3
   #- images/Poland.jpeg
   #- images/Spain.jpeg
   #- images/France.jpeg
   #- images/Italy.jpeg

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
